### ISSUE TITLE
Some thoughts.

### ISSUE THREAD

**Issue by willjgriff** [fmorisan/hnylp-twap-drip#2]
- I would suggest merging the start drip function with the constructor to avoid any possibility that drip() is called before startDrip(). I don't see any reason for them to be separate.
- Use safemath here: https://github.com/fmorisan/hnylp-twap-drip/blob/master/contracts/Dripper.sol#L137
- You shouldn't rely on an external approval amount for anything, especially the total amount to drip, this can change easily. I know in this case it's unlikely too because it would require a vote but you should record either the totalAmountToDrip or the endTime of the drip in the contract and use that to calculate the end of the drip: https://github.com/fmorisan/hnylp-twap-drip/blob/master/contracts/Dripper.sol#L145
- Couldn't endTokenToAddAsLiquidity be larger than expectedOutput reverting here? https://github.com/fmorisan/hnylp-twap-drip/blob/master/contracts/Dripper.sol#L186 
- I would recommend adding a pause/cancel feature incase it starts behaving incorrectly.

**Comment by fmorisan** [comment]
Regarding your comment on line 186, `expectedOutput` does not take into account pool fees, since it is calculated based only on the pool reserves. In practice, this means that `endTokenToAddAsLiquidity` is *always* going to be less than our `expectedOutput` by at least the pool swap fees (which I think in Honeyswap's case are set to 0.5%).

**Comment by fmorisan** [comment]
Regarding the `approval` amount comment, this is only used to avoid reverting in case we can't consume enough LP tokens to cover the current drip, adjusting to the possible amount. I agree that this might not be the best solution. Will change the behaviour to try to drip the required amount, and if `transferFrom` fails then revert anyway.

This might lead to a situation where the last drip doesn't go through because of accumulated rounding errors though, where we might be off by a few *wei* to *kwei* at the last drip time.

Note that the amount to drip is calculated from the initially set total amount, and this approval check is only used to correct the amount in this kind of situations.

**Comment by fmorisan** [comment]
- [ ] startDrip vs drip(): Differentiated the functions but there is a need for this behaviour. Approval needs to be set for a deployed contract, if we deploy the contract and it starts counting time right away we will have a big accumulated drip value by the time we can finally call drip().

- [X] Use safemath here: https://github.com/fmorisan/hnylp-twap-drip/blob/master/contracts/Dripper.sol#L137
- [X] Removed approval() check
- [X] See above comment, 
  - > Regarding your comment on line 186, `expectedOutput` does not take into account pool fees, since it is calculated based only on the pool reserves. In practice, this means that `endTokenToAddAsLiquidity` is _always_ going to be less than our `expectedOutput` by at least the pool swap fees (which I think in Honeyswap's case are set to 0.5%).
- [X] Added an abort() call.
cc @willjgriff
